exclude: ^.*\bMigrations\b
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: detect-private-key
      - id: mixed-line-ending
      - id: check-merge-conflict
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.22.0
    hooks:
      - id: eslint
        exclude: ^.*\b(node_modules|bin|obj)
        args: ["-c /ConfigCheckerSpa/eslint.config.mjs"]
        additional_dependencies:
          - "@eslint/js@9.22.0"
          - "@stylistic/eslint-plugin-js@4.2.0"
          - globals@16.0.0
